PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dwh: <http://sekmi.de/histream/dwh#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
SELECT ?label ?description ?notation ?type 
WHERE {
	?concept skos:prefLabel ?label

	OPTIONAL {?concept dc:description ?description}
	OPTIONAL {?concept skos:notation ?notation}
	OPTIONAL {?concept dwh:restriction ?type}


	FILTER ( EXISTS {?concept skos:narrower ?narrower} 
		|| EXISTS {?concept dwh:restriction ?type})
	FILTER( lang(?label) = 'de' )
	FILTER( !EXISTS{?concept dc:description ?description} || !regex(?description,"ICD"))
	FILTER( !EXISTS{?concept dc:description ?description} || !regex(?description,"(Tree)"))
#	FILTER (! regex(?description,"ICD","i"))

}
ORDER BY DESC(?type) ASC(?concept) ASC(?label)